"""User-writable directory for data, model, and persisted state.

Why this exists
---------------

Up until the auto-update system, the shipped overlay read its data
(parsed cards, 17Lands ratings, the choice model) from inside the
PyInstaller-frozen bundle (``sys._MEIPASS / "data"``). That's fine
for read-only state but means refreshing 17Lands ratings or pushing
a new model would require re-shipping the entire ~325 MB bundle.

We're moving toward a model where the bundle is mostly read-only
code + a one-time data seed, and the data itself lives in a
user-writable directory that an in-process updater can refresh
without restarting the overlay. This module is the foundation: it
defines the per-user paths and seeds them from the bundled defaults
on first launch (so the EXE works offline immediately, before any
auto-update has run).

Layout
------

Under ``%LOCALAPPDATA%\\MulliganCoach\\`` (and the macOS/Linux
equivalents), we maintain:

* ``data/processed/parsed_cards/<SET>.json`` — per-set ParsedCards.
* ``data/processed/seventeenlands/ratings/<SET>/PremierDraft.parquet``.
* ``models/choice_prod/{xgboost.json, metadata.json, sweep_results.json}``.
* ``_seeded_version.txt`` — version stamp of the bundle this seed
  came from. Compared against the bundle's ``_bundle_version.txt``
  on each launch to decide whether to re-seed when the user has
  upgraded the EXE.

The clean separation lets a later slice (the manifest fetcher)
atomically swap any of these files without touching the read-only
bundle.

Why a version stamp instead of mtime / hashing
----------------------------------------------

Two reasons:

* Extracting a ZIP can rewrite mtimes, so mtime comparisons can't
  reliably tell "bundle is newer" from "user just re-extracted".
* Hashing every bundled file on every launch is slower than reading
  one tiny version file.

The stamp is generated by ``build_distribution.py`` at build time
and ships inside the bundle. The format is opaque to this module —
we treat it as a string identifier and only test for equality.
"""

from __future__ import annotations

import logging
import os
import shutil
import sys
from pathlib import Path

log = logging.getLogger(__name__)


_BUNDLE_VERSION_FILE = "_bundle_version.txt"
"""Name of the version stamp file written by the build script.

Sits at the bundle root (the same dir as ``sys._MEIPASS`` points to
when frozen). Absent when running from source, which is fine —
``seed_from_bundle`` falls back to a "seed only if user dir is
missing" heuristic in that case.
"""

_SEEDED_VERSION_FILE = "_seeded_version.txt"
"""Mirror of the bundle version, written to the user dir after a
successful seed. Compared against the bundle's stamp on each launch.
"""


def user_state_root() -> Path:
    """Per-user state directory; created lazily by callers.

    Same root convention as :func:`_frozen.user_log_dir` and the
    existing ``deck_persistence`` / ``position_persistence`` modules,
    so all overlay state files cluster under one per-user folder:

    * Windows: ``%LOCALAPPDATA%\\MulliganCoach\\``
    * macOS: ``~/Library/Application Support/MulliganCoach``
    * Linux: ``$XDG_DATA_HOME/MulliganCoach`` or
      ``~/.local/share/MulliganCoach``

    No directory is created here — the seed step does that once it
    knows there's something to write. Pure path resolution.
    """
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA")
        root = Path(base) if base else Path.home() / "AppData" / "Local"
    elif sys.platform == "darwin":
        root = Path.home() / "Library" / "Application Support"
    else:
        xdg = os.environ.get("XDG_DATA_HOME")
        root = Path(xdg) if xdg else Path.home() / ".local" / "share"
    return root / "MulliganCoach"


def user_data_root() -> Path:
    """Where the recommend pipeline reads parsed_cards + 17Lands ratings.

    Mirrors the layout the recommend pipeline expects via the
    ``MULLIGAN_COACH_DATA_ROOT`` env var: under this dir you'll
    find ``processed/parsed_cards/<SET>.json`` and
    ``processed/seventeenlands/ratings/<SET>/PremierDraft.parquet``.
    """
    return user_state_root() / "data"


def user_models_root() -> Path:
    """Where the recommend pipeline reads the choice (and legacy win) model.

    Matches the bundled layout: e.g. the choice model lives at
    ``<user_models_root>/choice_prod/`` and is passed to the recommend
    service via ``MULLIGAN_COACH_CHOICE_MODEL_DIR``.
    """
    return user_state_root() / "models"


def seed_from_bundle(bundle_root: Path, *, force: bool = False) -> bool:
    """Copy bundled data + model files into the user state dir.

    Called on every launch of the frozen EXE; cheap when there's
    nothing to do. Re-seeds when:

    * The bundle has a ``_bundle_version.txt`` and the user dir
      either has no ``_seeded_version.txt`` or its stamp differs.
      Detects "user upgraded the EXE".
    * The user dir is missing the data / model subtrees entirely.
      Detects "first install".

    Stable launches (same bundle version, user dir already
    populated) skip the file copy entirely.

    With ``force=True`` the version comparison is bypassed and every
    bundled file is copied over the top. Useful for tests and for
    recovering from a partially-corrupted user dir.

    Returns ``True`` if any files were copied, ``False`` otherwise.
    """
    bundle_data_root = bundle_root / "data"
    bundle_models_root = bundle_root / "models"

    if not bundle_data_root.exists() and not bundle_models_root.exists():
        # Nothing to seed — running from source, or a malformed bundle.
        # The caller's path-resolution fallback handles the latter.
        log.debug(
            "seed_from_bundle: bundle has no data/ or models/ under %s; nothing to do",
            bundle_root,
        )
        return False

    bundle_version = _read_version(bundle_root / _BUNDLE_VERSION_FILE)
    state_root = user_state_root()
    seeded_version = _read_version(state_root / _SEEDED_VERSION_FILE)

    user_data_present = (state_root / "data").exists()
    user_models_present = (state_root / "models").exists()

    if (
        not force
        and bundle_version is not None
        and bundle_version == seeded_version
        and user_data_present
        and user_models_present
    ):
        # Up-to-date and complete; auto-update is now in charge.
        log.debug("seed_from_bundle: user dir already at bundle version %s", bundle_version)
        return False

    log.info(
        "seed_from_bundle: copying bundled data/model (bundle_version=%r, "
        "seeded_version=%r, data_present=%s, models_present=%s, force=%s)",
        bundle_version,
        seeded_version,
        user_data_present,
        user_models_present,
        force,
    )
    state_root.mkdir(parents=True, exist_ok=True)
    if bundle_data_root.exists():
        _copy_tree(bundle_data_root, state_root / "data")
    if bundle_models_root.exists():
        _copy_tree(bundle_models_root, state_root / "models")

    if bundle_version is not None:
        (state_root / _SEEDED_VERSION_FILE).write_text(bundle_version, encoding="utf-8")
    return True


def _copy_tree(src: Path, dst: Path) -> None:
    """Recursive copy preserving the directory layout.

    ``shutil.copytree(dirs_exist_ok=True)`` is idempotent against
    partially-seeded user dirs (a previous run that crashed mid-copy
    can resume safely) and overwrites existing files in place — the
    semantics we want for an EXE upgrade where the bundled artifacts
    are authoritative.
    """
    shutil.copytree(src, dst, dirs_exist_ok=True)


def _read_version(path: Path) -> str | None:
    """Read a version stamp file, returning ``None`` if missing or unreadable.

    Stamps are short ASCII strings (timestamp + git hash). Any read
    error is logged and treated as "no stamp" — that makes seeding
    over-eager rather than skipping a needed seed because the user
    deleted a file by hand.
    """
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8").strip() or None
    except OSError as exc:
        log.warning("could not read version stamp %s: %s", path, exc)
        return None
